name: Seu Workflow de Deploy/Teste

on:
  push:
    branches:
      - main # Ou a branch que você usa para deploy/teste

jobs:
  seu_job_de_backend: # Nome do seu job, por exemplo, 'deploy-backend'
    runs-on: ubuntu-latest
    environment: mongodb-backend # <--- ESTA LINHA É CRÍTICA!
                                 # Ela vincula este job ao ambiente 'mongodb-backend'
                                 # e dá acesso ao secret MONGODB_URI.

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a versão do Python que seu projeto usa

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Certifique-se que pymongo e dnspython estão aqui

      - name: Executar Aplicação ou Teste de Conexão
        # A variável MONGODB_URI estará disponível como uma variável de ambiente normal
        # para o script executado neste passo, sem precisar de `env:` explícito aqui.
        run: |
          echo "A variável MONGODB_URI está definida no ambiente de execução."
          # Seu script Python irá ler MONGODB_URI usando os.getenv("MONGODB_URI")
          python seu_script_principal.py
          # Ou se for um script de teste de conexão:
          # python test_connection.py
